version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: frontend-dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
