name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Audit npm dependencies
        run: npm run audit:ci
        working-directory: frontend
        
      - name: Run npm audit with Docker
        run: npm run audit:docker
        working-directory: frontend
        
      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=
            -Dsonar.projectKey=
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            
  build-deploy:
    needs: build-audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
        
      - name: Build project
        run: npm run build
        working-directory: frontend
        env:
          PROJECT_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend